### ISSUE TITLE
Create Shopping Item

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-new-shopping-buddy#1]
# Create Shopping Item

## Value Proposition

**As a user**

**I want to** add new items to my shopping list,

**so that** I can keep track of what I need to buy.

## Description

![Image](https://github.com/user-attachments/assets/cd40ec5c-16dc-47e7-8e1a-1d54209a8725)

## Acceptance Criteria

- A form for adding shopping items is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
  - Shopping item comment
- The following fields are mandatory:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- The category is selected from the existing categories list via a dropdown menu.
- The categories dropdown must include a default option, "Please select a category", and necessitates a selection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new item is added to the top of the shopping list.

## Tasks

- [ ] Create feature branch `feature/create-shopping-item`
- [ ] The category options are listed in the [`categories.json`](./assets/categories.json) file
- TASKS:
- [ ] create a ShoppingItemForm component with 3 mandatory fields: name, quantity and category, so users can add new shopping items
- [ ] implement a dropdown menu for the shopping item category

> 💡 It is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a shopping item.

----

### 📒 Handout/Link List
- [react-state-2: Handling Form Data](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-2/react-state-2.md#handling-form-data)
- [react-state-3: Updating Arrays of Objects in State / adding a new object](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-3/react-state-3.md#adding-a-new-object)
