### ISSUE TITLE
Design Overhaul - Layout and UX

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-new-shopping-buddy#16]
## Value proposition

As a **user**
I want to encounter a **visually appealing design and intuitive options** when I use the app
so that I have a smooth and pleasant experience.

## Description

![Image](https://github.com/user-attachments/assets/8363505b-4d26-4551-9456-991a3bb552b8)

The above wireframe contains only a selection of the applied changes. 

## Acceptance criteria

- The page has a **header** that contains the name of the page, 
the title of the main grocery list, a "back to welcome page" button, the number of items on the main list and a message including the number of items on the current list
- List items use a **font** reminiscent of handwriting giving the app a nostalgic touch
- The website uses copyright-free **pictures**
- The distinction between **buttons and links** on the one hand and **labels** on the other is obvious
- **icons** represent the basic buttons (such as "add" and "return to welcome page")
- **boxes and other elements** look appealing with subtle shadows around the edges 
- The **colours** of the website are harmonic and consistent
- The layout of the different elements is **coherent** with matching colours and styles that recur in different elements
- When I click on the "add" or on the "edit" button, the **page scrolls** to the respective form so that the form is fully visible on the screen
- The **distribution of elements** is flexible and is adapted to the respective screen size in a sensitive way
- Relevant elements include **aria labels** that make the page more easily accessible for people with special needs and allow screen readers to access the content of the website

## Tasks

- [ ] new from US mark as purchased:
      -- [ ] Instead of nesting the input element inside the label element, connect label and input via 
          htmlFor and id attribute, do that for all your form elements in order to be consistent.
     -- [ ] replace asterisk in form with [asterisk icon](https://www.svgrepo.com/svg/431437/asterisk) and add the text "required" as a visually hidden element, as described in (https://www.accessibility-developer-guide.com/examples/forms/required/#better-approach-using-an-icon)    
    -- you’ve uploaded some images to your project that you’re not actually using. I strongly recommend that you only use images that aren’t copyrighted (e.g., from Unsplash). Additionally, you can simply store the image URL in your state instead of saving the image files in your project.
   -- I strongly suggest to not use any inline styles. You should use styled components instead.
   -- I understand that you want to differentiate between singular and plural here. Beyond that, I wouldn’t adjust the wording. In my opinion, it doesn’t add much value and only complicates the code unnecessarily. I suggest keeping it simple.
   -- shoppingItem.js line 28-40: In this case you do not really need a form. In order to toggle the label of the checkbox, you can use the isPurchased key of your shoppingItem
   -- make sure that only one element at a time can be in non-default mode (edit/delete)
- [ ] Create a feature branch 'design overhaul'
- [ ] List the tasks that need to be performed within the dev team
- [ ] Change persisting inline-styles to global styles
- [ ] Create a header using flexbox 
- [ ] Include a message displaying the number of items on the current list or excerpt
- [ ] use separate elements for text and (variable) number so that the text does not "jump" 
when the number changes 
- [ ] Implement a "back to homepage"-button using an icon in the header
- [ ] Use an icon for the "add"-button
- [ ] Implement a font reminiscent of handwriting in the list elements
- [ ] Replace current pictures with pictures from unsplash to avoid copy right issues
- [ ] Rather than the actual picture files include only their url-s in the code
- [ ] Make the distinction between **buttons, links and labels** obvious (and at the same time pleasantly subtle); 
- [ ] Make sure labels aren't displayed in boxes that resemble buttons
- [ ] Use hover to have links and buttons stick out
- [ ] Use icons - at least for the basic buttons - and add a logo and a favicon
- [ ] Make boxes and other elements look appealing with background and shadows around the edges 
- [ ] Optimize color palette
- [ ] Implement a scroll upon click function for the "add"- and "edit"-buttons
- [ ] Make sure the layout of the different elements is coherent with matching colors and styles that recur in different elements
- [ ] Make sure elements don't overlap (esp. on the details page)
- [ ] Make sure the distribution of elements is variable and is adapted to the respective screen size in a sensitive way using flexbox and global styles
- [ ] Add aria labels in order to make the page more easily accessible to people with special needs and to allow screen readers to access the content of the website

## Notes and Links

- include accessibility (see links in slack 24-08-20)
- look at other websites for layout inspiration
- see links below for "scroll to form upon click/submit": 

[https://www.w3schools.com/JSREF/met_element_scrollintoview.asp](https://www.w3schools.com/JSREF/met_element_scrollintoview.asp)

[https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)
