### ISSUE TITLE
Shopping Item Details

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-new-shopping-buddy#5]
# Shopping Item Details

## Value Proposition

**As a user**

**I want to** access detailed information about each item in my shopping list,

**so that** I can make informed decisions about what to buy.

## Description

![Image](https://github.com/user-attachments/assets/1ad51ca1-2867-4dd0-9547-b2febba16a03)

## Acceptance Criteria

- Each item in the shopping list has a link to a details page.
- Each details page contains:
  - Shopping item name
  - Shopping item image
  - Shopping item quantity
  - Shopping item category
  - Shopping item comments
- The detailed view includes a “back” link, allowing users to easily navigate back to the shopping list.

## Tasks

- [ ] Create feature branch `feature/shopping-item-details`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
- [ ] If not done yet, add an `imageUrl` for each shopping item, for example from [unsplash.com](unsplash.com).
- [ ] Capstone Student Todo: Add tasks

- TASKS:
- [ ] if not done yet, create an ItemDetails page
- [ ] import link
- [ ] import styles
- [ ] import fonts
- [ ] import pictures
- [ ] implement dynamic path to the details page
- [ ] insert dynamic links to details pages

### 📒 Handout/Link List
- [next-dynamic-routes](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/nextjs-dynamic-routes/nextjs-dynamic-routes.md)
  - Knowing implement dynamic paths - for the details page of a item
  - Knowing how to generate links dynamically - link to a details page
