### ISSUE TITLE
Shopping Items List

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-new-shopping-buddy#6]
# Shopping Items List

## Value Proposition

**As a user**

**I want to** browse a well-organised list of shopping items,

**so that** I can easily see what I need to buy.

## Description

![Image](https://github.com/user-attachments/assets/6aac569b-5dae-44da-a31d-7571f1d2de0c)

## Acceptance Criteria

- The homepage displays a list of shopping items.
- The shopping list is headlined with its purpose.
- Each item listing includes:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- A counter displays the total number of items currently on the shopping list.
- Each category is visually differentiated, for example, by using different colours.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/shopping-items-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
  - [ ] Add an `imageUrl` for each shopping item, for example from [unsplash.com](unsplash.com). You first need the image in the User Story [Shopping Item Details](./shopping-item-details.md)
- [ ] Capstone Student Todo: Add tasks

TASKS:

- [ ] create `lib` folder with `data.js`
- [ ] write variables for `categories` and `shopping-items` in `data.js`, replace `ids` by `slacks` for `shopping-items`, add `colors` for `categories`
- create folder `images` in `public` folder and add sample picture in `.png` format

- [ ] In index.js replace title
- [ ] paste `assets folder` with `categories.json` and `shopping-items.json` into project folder
- [ ] in `ItemsList`: 
    - [ ] import the two arrays 
    - [ ] write a default export function `ItemsList` 
            which returns the component ShoppingItem as list element as often as necessary 
            by mapping over the array using the ID and returning a list element for each array item which contains name, quantity and category
 
- [ ] add function Counter which returns the total number of items, i.e. of different items, irrespective of the number of each individual item
            - use array.length
- in order to visually differentiate categories, add a color to each category in the category array and adapt the background color accordingly, i.e. create different css classes and render them conditionally depending on the category

- either now or postpone to next UserStory:

    - [ ] Create `components` folder
    - [ ] create a component ShoppingItem
    - [ ] in this component, write a  default export function which returns a single ShoppingItem
    
----

### 📒 Handout/Link List
- [React with Arrays](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-with-arrays/react-with-arrays.md)
  - Knowing how to use `.map()` to render lists in JSX
  - Understanding how to render items from an array of objects
  - Knowing to add a unique key for list items
