### ISSUE TITLE
Update Shopping Item

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-new-shopping-buddy#7]
# Update Shopping Item

## Value Proposition

**As a user**

**I want to** edit existing shopping items in my shopping list,

**so that** I can correct errors or update information as needed.

## Description

![Image](https://github.com/user-attachments/assets/82bb7f0d-05d3-4c58-a3b7-6ac670de37ca)

## Acceptance Criteria

- Each shopping item in the shopping list includes an easily accessible edit option.
- Clicking the edit option opens a form pre-filled with the shopping item’s existing details for modification.
- The form allows for edits to all item details, including:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
  - Shopping item comment
- The following fields are mandatory:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- The form includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty mandatory fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is redirected back to the shopping list, and the changes are saved and reflected.

## Tasks

- [ ] Create feature branch `feature/update-shopping-item`
- [ ] reuse the create shopping item form component: with 3 mandatory fields and a dropdown menu 
- [ ] add a button in the ShoppingItem component that opens up the add/edit form
- [ ] create a state with 2 options plus unmarked as needed for 2 versions of the add/edit form and closing the form 
- [ ] implement two variants of the form, chosen depending on the mode
- [ ] in order to pre-fill the edit form and save changes, set the "editedItem" (i.e. the item that is in the state of being edited)
- [ ] add buttons for saving or cancelling the edit (toggle state)

> 💡 It is not yet possible to edit images at this stage.

### 📒 Handout/Link List
- [react-state-2: Handling Form Data](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-2/react-state-2.md#handling-form-data)
- [react-state-3: Updating Arrays of Objects in State / replacing an object](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-3/react-state-3.md#replacing-an-object)
- React Documentation [Providing an initial value for an input](https://react.dev/reference/react-dom/components/input#providing-an-initial-value-for-an-input)

**Comment by ahohnsen** [comment]
Hey Rebecca,

I suggest to reuse the "create"-form component instead of creating a new form component for the edit process.

**Comment by rvoll** [comment]
Ich habe die US jetzt nochmal abgeändert, so dass der "create"-form component wiederverwendet wird.
